location __PATH__/ {
    alias __INSTALL_DIR__/public/;
    try_files $uri $uri/ __PATH__/index.php?$query_string;

    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php__PHP_VERSION__-fpm-__APP__.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME __INSTALL_DIR__/public/index.php;
    }
}

