packaging_format = 2
id = "librepress"
name = "LibrePress"
description.en = "Modern modular Laravel CMS"
description.fr = "CMS Laravel moderne et modulaire"
version = "0.1.0~ynh1"
maintainers = ["LibrePress maintainers"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://example.org"
code = "https://example.org/librepress"

[integration]
yunohost = ">= 12.0"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "256M"
ram.build = "512M"
ram.runtime = "256M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/librepress"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

